name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vérifier les fichiers
        run: |
          test -f nginx.conf
          test -f index.html
          test -f Dockerfile

      - name: Tester le service
        run: |
          # construction d'image docker
          docker build -t ci-cd-nginx-test .
          # lancement du conteneur
          docker run -d -p 8080:80 --name nginx-test ci-cd-nginx-test
          sleep 2
          # test http
          curl -f http://localhost:8080/
          curl -f http://localhost:8080/health
          docker stop nginx-test
